server:
  port: 8111

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:111.230.52.145}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:chen226}
    #连接超时时间
    timeout: 5000

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCFYHwNJPeG/djTGEf4423uNtAXuakIO3mScAGVZ93+eQCZVynbNINMyOzDxwYsONKm2fpPEgpZKY1g7RfAV4fHNQwwC14/Qi29671vomdrE3P/EJHKKv85+8qTq4gNnSRe8IiyKrqYqbmM2dA9DtLyOwjX1MgUw0m11wTcJQ7dzFuVfa4FB+YsBYP3j/mOYrGAco3S78HL0+E7p35r+oux4N30w3ZkM6VUSaqwX6NVz8stNMvzHu49VzPAkSLHt1eaEYxxk3QWv1x/KNMSoBg5P57mpO7g7gFXsi6VDFHnhdGGso2mf0ooIBh9bKTBzsjn7lqR8fGIOY53wkg8hG+nAgMBAAECggEBAITPIHdOOhP3LTJ12STiAhLUDb2yJ7iE0HeahFkrRgggoRIPkyQtVBjfcbM4uNLL+iYeo3qcsiU6lQbQz3e9MPyRvAMTLtO6qCWXWdiRVH1wr25qJ2GyEta//GWyxhUYRqEqzlLq7UcaqiKwuQQzgKWnVxTjUiAqnXkuFC7Jz9XWOUU+B97ZxfL83lgkDkbFQRqMV+wkw4KYNLIUoVo0epMTN2+s+Q/CWfc6j5OjKYZfkdTxMtY5q9PZ7yqD3uVegNEW5LB1s/fw2PG3v/Wji/KVs+an0PiQSYA/JkCuANWOBys2Px8AlESgU6uKaEFbMh6n5YcaADjwMAnUkzLLTiECgYEAw0MSFeKCHwRvzWjHMy6IMrwjzZ/88mL5FERsLWmh8iTjxvagHXOtNWwnLiISdD6z8hXVhlehbg5HO9P46v+WXCjUmmwJ3sNKv4ggkMadckOsRYaXKj7eIFFC0FXTTPQ9gqIWVb9FMP9kwRlY4y92wwj1k7XrsvKARIOph4qWNpkCgYEArt1vQP8DkvYlNQ0jlpMeouO7bb7sIH+Nu/yBuAdiPT0wpHbgDR91/lM2PTNNoGihR8kRNQ4XcU1hIQrL+pRtcEiHBrCg/E+lqVfoxGvtzbyj3tSeolJsIyW0rQLtSTHVX1s/owhQVAd0nEkGTSorcfyG2vbb2zrkPZ6vYz8VAD8CgYEAwBqTh35yoEuAJ2nnWT51dtzMqLe3Z0ziWwM6Hq+nSZDrm8r2GiO9jCqcnXGeEEnERe8fRO2f/6QChyTz51ePuZneGRMj3srqFme6ClWtf0Z/DWPuAv0ZEliAUHGv0i0U+xm2uaPVUfBiUuw6HEGNKTL+UNWRT1vvv/h86MH7KTkCgYAiJb/aE3KhOkwdxgkTGHu9F3e8gLIfzojhEvhJ9bcrek2LcGNkbKZgGePXo7MfBg+osw0XLT9Ksu+qwi7/KgkNCjzEA64MV4lkPnSIFwODT7k4hJDN5gaT/oL/3jh0OLUQQAN3VOJK5oHRGzmNzBRb2BKFo/tfHmr/1YMugF0bhQKBgBR+uMj19m5+k/IDt7nhCLNABhiSsbwe1VlngmOLnJovwOt/1hhswr/wSGFvuV6YHdgoneXVsU2HkX9hAfNF7nq4S/sXb/cGl4RR6ie+r7ixdSQ0df2i3EFFdzFpnPletF+09/gFU0p8/fdYcYpjCp3Z9mQ0iK0OgTmfpAmUj47O
